SiteBMS/Models/Utilisateur.cs
namespace SiteBMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Utilisateur")]
    public partial class Utilisateur
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string Nom { get; set; }

        [StringLength(50)]
        public string Prenom { get; set; }

        [Required]
        [StringLength(50)]
        public string Login { get; set; }

        [Required]
        [StringLength(50)]
        public string PassWord { get; set; }

        public int? RefLangue { get; set; }

        [NotMapped]
        public string LangueName { get; set; }

        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        public bool IsActive { get; set; }

        public int RefRole { get; set; }

        public int RefId { get; set; }

        public virtual RoleUtilisateur RoleUtilisateurs { get; set; }
    }
}

SiteBMS/ViewModels/UtilisateurViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using SiteBMS.Models;

namespace SiteBMS.ViewModels
{
    public class UtilisateurViewModel
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Name", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Nom")]
        public string Nom { get; set; }

        [StringLength(50)]
        [Display(Name = "FirstName", ResourceType = typeof(Resources.Resources))] //[Display(Nom = "Prénom")]
        public string Prenom { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "UserName", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Login")]
        public string Login { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Password", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Mot de passe")]
        public string PassWord { get; set; }

        //[Required(ErrorMessageResourceType = typeof(Resources.Resources),
        //      ErrorMessageResourceName = "EmailRequired")]
        /*
        [Display(Name = "PasswordField", ResourceType = typeof(My.Resources.Resource))]
        [MinLength(6, ErrorMessageResourceName = "PasswordLengthError", ErrorMessageResourceType = typeof(My.Resources.Resource))]
        [Compare("PasswordAgain", ErrorMessageResourceName = "CompareError", ErrorMessageResourceType = typeof(My.Resources.Resource))]
        [Required(AllowEmptyStrings = False, ErrorMessageResourceName = "RequiredPassword", ErrorMessageResourceType = typeof(My.Resources.Resource))]
        */
        //[Compare("PassWord", ErrorMessage = "Le mot de passe ne correspond pas, saissez le à nouveau! ErrorPassword")]

        /*
                [NotMapped]
                [Display(Name = "Confirmer le mot de passe")]
                [Compare("PassWord", ErrorMessage = "Le mot de passe ne correspond pas, saissez le à nouveau!")]
                public string ConfirmPassword { get; set; }

        */

        [NotMapped]
        [Display(Name = "ConfirmPassword", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Confirmer le mot de passe")]
        [Compare("PassWord", ErrorMessageResourceName = "ErrorPassword", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Language", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Langue")]
        public int? RefLangue { get; set; }

        [NotMapped]
        [Display(Name = "Language", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Langue")]
        public string LangueName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Email", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Activated", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Activé")]
        public bool IsActive { get; set; }

        [Display(Name = "Role", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Rôle")]
        public int RefRole { get; set; }

        [Display(Name = "Technician", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Technicien")]
        public int RefId { get; set; }

        [Display(Name = "Role", ResourceType = typeof(Resources.Resources))] // [Display(Name = "Rôle")]
        public virtual RoleUtilisateur RoleUtilisateurs { get; set; }

        [NotMapped]
        public TechnicienViewModel Technicien { get; set; }

        //provide origin of action (from distributeur/client) when update or add utilisateur
        [NotMapped]
        public string Origin { get; set; }

        public string FullName => Utils.UcFirst(Prenom) + " " + Utils.UcFirst(Nom);
    }
}

SiteBMS/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Newtonsoft.Json;
using PagedList;
using SiteBMS.DAL.Security;
using SiteBMS.Models;
using SiteBMS.ViewModels;

namespace SiteBMS.Controllers
{
    public class UtilisateursController : BaseController
    {
        private readonly int[] roles = new[] { (int)RoleType.Pdg, (int)RoleType.ResponsableZone, (int)RoleType.Technicien };

        // GET: Utilisateurs
        public ActionResult Index(string sortOrder, string currentFilter, int? page, string searchString, int? refLangue)
        {
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "SortDesc" : ""; // name_desc
            ViewBag.SortingClass = "SortDesc";
            ViewBag.PaysSortParm = sortOrder == "Pays" ? "PaysDesc" : "Pays";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.RefLangue = refLangue;
            ViewBag.CurrentSort = sortOrder;

            var utilisateurs = (from t in db.Techniciens
                                join r in db.Techniciens on t.RefRespZone equals r.ID
                                join u in db.Utilisateurs.Where(ro => roles.Contains(ro.RefRole)) on t.ID equals u.RefId
                                where t.RefRespZone == User.RefId
                                || r.RefRespZone == User.RefId
                                || u.RefId == User.RefId
                                || User.RefId == (int)RoleType.Pdg
                                orderby u.Nom
                                select u).ToList();

            if (refLangue != null)
            {
                utilisateurs = utilisateurs.Where(s => s.RefLangue == refLangue).ToList();
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                utilisateurs = utilisateurs.Where(s => s.Nom.StartsWith(searchString,StringComparison.InvariantCultureIgnoreCase)).ToList();
            }

            var utilisateurVm = MapperConfig.mapper.Map<List<Utilisateur>, List<UtilisateurViewModel>>(utilisateurs);

            var langues = new SelectList((from l in db.Langues
                                          join t in db.Traductions on l.Nom_T equals t.RefElement
                                          where l.IsActive && t.RefLangue == User.LanguageId
                                          select new { l.ID, Name = t.Traduction1 }), "ID", "Name", refLangue);

            ViewBag.DDLLangues = langues;

            utilisateurVm.ToList()
                .ForEach(u => u.LangueName = langues.Where(l => l.Value == u.RefLangue.ToString()).Select(l => l.Text).FirstOrDefault());

            // Sort by sortOrder parameter if set
            switch (sortOrder)
            {
                case "SortDesc":
                    utilisateurVm = utilisateurVm.OrderByDescending(s => s.Nom).ToList();
                    break;

                case "PaysDesc":
                    utilisateurVm = utilisateurVm.OrderByDescending(s => s.RefLangue).ToList();
                    break;

                case "Pays":
                    utilisateurVm = utilisateurVm.OrderBy(s => s.RefLangue).ToList();
                    break;
            }

            var pageNumber = (page ?? 1);
            return View(utilisateurVm.ToPagedList(pageNumber, pageSize));
        }

        // GET: Utilisateurs/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            var utilisateurVm = MapperConfig.mapper.Map<Utilisateur, UtilisateurViewModel>(utilisateur);
            InitViewBag(utilisateurVm);
            ViewBag.Page = (page ?? 1);

            return View(utilisateurVm);
        }

        // GET: Utilisateurs/Edit/5
        public ActionResult Edit(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }

            var utilisateurVm = MapperConfig.mapper.Map<Utilisateur, UtilisateurViewModel>(utilisateur);
            InitViewBag(utilisateurVm);
            ViewBag.Page = (page ?? 1);
            return View(utilisateurVm);
        }

        // POST: Utilisateurs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UtilisateurViewModel utilisateurVm)
        {
            if (ModelState.IsValid)
            {
                var utilisateur = MapperConfig.mapper.Map<UtilisateurViewModel, Utilisateur>(utilisateurVm);
                db.Entry(utilisateur).State = EntityState.Modified;

                // change PaysId and LanguageId inside actual cookie for impact UI language immediately
                if (User.LanguageId != utilisateur.RefLangue && utilisateur.ID == User.UserId )
                {
                    // convert language to contry ID
                    var actualUserPays = Repositories.ConvertLangueToPays(db, utilisateur?.RefLangue ?? 1);

                    User.PayId = actualUserPays;
                    User.LanguageId = utilisateur?.RefLangue ?? 1;

                    var authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
                    if (authCookie != null)
                    {
                        var authTicket = FormsAuthentication.Decrypt(authCookie.Value);

                        if (authTicket != null)
                        {
                            var userData = JsonConvert.DeserializeObject<CustomPrincipalSerializeModel>(authTicket.UserData);

                            userData.LanguageId = User.LanguageId;
                            userData.PayId = User.PayId;
                            var newUserData = JsonConvert.SerializeObject(userData);

                            var newAuthTicket = new FormsAuthenticationTicket(
                                1,
                                authTicket.Name,
                                DateTime.Now,
                                DateTime.Now.AddMinutes(30),
                                authTicket.IsPersistent,
                                newUserData);

                            var encTicket = FormsAuthentication.Encrypt(newAuthTicket);
                            var faCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
                            Response.Cookies.Add(faCookie);
                        }
                    }
                }

                db.SaveChanges();

                if (utilisateurVm.Technicien != null && roles.Contains(utilisateurVm.RefRole))
                {
                    var technicien = MapperConfig.mapper.Map<TechnicienViewModel, Technicien>(utilisateurVm.Technicien);
                    db.Entry(technicien).State = EntityState.Modified;
                    db.SaveChanges();
                }

                // redirection by Role
                if (User.IsAuthorized(new[] { RoleType.Pdg, RoleType.ResponsableZone }))
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index", "Home");
            }

            InitViewBag(utilisateurVm);
            return View(utilisateurVm);
        }

        // GET: Utilisateurs/Create
        public ActionResult Create()
        {
            var utilisateurVm = new UtilisateurViewModel
            {
                PassWord = "",
                Technicien = new TechnicienViewModel(),
                RefId = 0,
                RefRole = 0
            };
            InitViewBag(utilisateurVm);

            return View(utilisateurVm);
        }

        // POST: Utilisateurs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UtilisateurViewModel utilisateurVm)
        {
            if (ModelState.IsValid)
            {
                if (utilisateurVm.Technicien != null && roles.Contains(utilisateurVm.RefRole))
                {
                    var technicien = MapperConfig.mapper.Map<TechnicienViewModel, Technicien>(utilisateurVm.Technicien);
                    db.Techniciens.Add(technicien);
                    db.SaveChanges();
                    utilisateurVm.RefId = technicien.ID;
                }

                var utilisateur = MapperConfig.mapper.Map<UtilisateurViewModel, Utilisateur>(utilisateurVm);
                db.Utilisateurs.Add(utilisateur);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            InitViewBag(utilisateurVm);
            return View(utilisateurVm);
        }

        private void InitViewBag(UtilisateurViewModel utilisateur)
        {
            ViewBag.DLLRefId = new SelectList((from t in db.Techniciens
                                               join u in db.Utilisateurs on t.ID equals u.RefId
                                               where u.RefRole == (int)RoleType.Technicien
                                               orderby u.Nom
                                               select new
                                               {
                                                   t.ID,
                                                   Name = u.Nom + " " + u.Prenom

SiteBMS/Views/Utilisateurs/Delete.cshtml
@model SiteBMS.Models.Utilisateur

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilisateur</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoleUtilisateurs.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleUtilisateurs.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassWord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassWord)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefLangue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefLangue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SiteBMS/Views/Utilisateurs/Details.cshtml
@model SiteBMS.ViewModels.UtilisateurViewModel
@{
    ViewBag.Title = Resources.Detail;
    Layout = "~/Views/Shared/_Layout.cshtml";

    // Required define a asterisc icon for mandatory field
    // See App_Start/Extentions.cs
    Func<dynamic, HelperResult> required = @<i class='fa fa-star asterisc'></i>;
    //var referrer = Request.UrlReferrer;
}

<div class="row">
    <div class="col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <!-- BREADCRUMB -->
                <h2>
                    @if (!User.IsAuthorized(RoleType.Client))
                    {
                        <a href="@Url.Action("Index", "Utilisateurs", new {page = ViewBag.Page})"><i class="fa fa-bars"></i> @Resources.UserS</a>
                        <i class="fa fa-chevron-right" style="font-size: 0.8em;"></i>
                    }
                    @ViewBag.Title
                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    <div class="form-horizontal">

                        <input type="hidden" name="referer" value="@Request.UrlReferrer.LocalPath" />

                        <!-- INFORMATION PERSONNEL -->
                        <div class="x_panel">
                            <div class="x_title">

                                <div class="col-md-10 col-sm-10">
                                    <h4 style="font-size:16px"><i class="fa fa-user"></i> @Resources.PersonalInfos</h4>
                                </div>
                                <div class="col-md-2 col-sm-2">
                                    <h5 class="pull-right">

                                        @if (Model.IsActive)
                                        { <span style="color:#169F85 !important"><i class="fa fa-info"></i> @Resources.Activated</span>}
                                        else
                                        { <span style="color:#d43f3a !important"><i class="fa fa-info"></i> @Resources.Deactivated</span>}
                                    </h5>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">

                                <div class="x_content">

                                    <div class="form-group">
                                        <!-- NAME -->
                                        @Html.LabelFor(model => model.Nom, null, required, new { @class = "control-label col-md-2" })
                                        <div class="col-md-4">
                                            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control",  @disabled = "disabled" } })
                                        </div>
                                        <!-- FIRST NAME -->
                                        @Html.LabelFor(model => model.Prenom, null, required, new { @class = "control-label col-md-2" })
                                        <div class="col-md-4">
                                            @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control",  @disabled = "disabled" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <!-- EMAIL -->
                                        @Html.LabelFor(model => model.Email, null, required, new { @class = "control-label col-md-2" })
                                        <div class="col-md-4">
                                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                        <!-- LANGUAGE -->
                                        @Html.LabelFor(model => model.RefLangue, new { @class = "control-label col-md-2" })
                                        <div class="col-md-4">
                                            @Html.DropDownListFor(model => model.RefLangue, ViewBag.DLLanguages as SelectList,
                                            new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <!-- INFORMATION COMPTE -->
                        <div class="x_panel x_top">
                            <div class="x_title">
                                <h4 style="font-size:16px"><i class="fa fa-sign-in"></i> @Resources.ConnectionInformation</h4>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">

                                <!-- LOGIN -->
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Login, null, required, new { @class = "control-label col-md-4" })
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                    </div>
                                </div>

                                @if (Model.ID == User.UserId || User.IsAuthorized(RoleType.Pdg))
                                {
                                <!-- PASSWORD -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.PassWord, null, required, new { @class = "control-label col-md-4" })
                                        <div class="col-md-4">
                                            <div class="input-group">
                                                @Html.PasswordFor(model => model.PassWord, new { @class = "form-control", value = Model.PassWord, @disabled = "disabled" })
                                                <div id="clearPassword" class="form-control"></div>
                                                <div class="input-group-addon btn" id="show-password">
                                                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }

                                @if (!User.IsAuthorized(RoleType.Client))
                                {
                                <!-- ROLES -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.RefRole, null, required, new { @class = "control-label col-md-4" })
                                        <div class="col-md-4">
                                            @Html.DropDownListFor(model => model.RefRole, (IEnumerable<SelectListItem>)ViewBag.DDLRefRole,
                                            new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>

                                <!-- TECHNICIENS -->
                                    @*<div class="form-group">
                                        @Html.LabelFor(model => model.RefId, new { @class = "control-label col-md-4" })
                                        <div class="col-md-4">
                                            @Html.DropDownListFor(model => model.RefId, (IEnumerable<SelectListItem>)ViewBag.DLLRefId,
                                            new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>*@

                                <!-- responsable -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Technicien.RefRespZone, null, null, new { @class = "control-label col-md-4" })
                                        <div class="col-md-4">
                                            @Html.DropDownListFor(model => model.Technicien.RefRespZone, ViewBag.DLLResponsables as SelectList, @Resources.InChargeOf,
                                        new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                        <!-- BUTTON -->
                        <div class="form-group x_panel">
                            <label class="control-label col-md-4">&nbsp;&nbsp;</label>
                            <div class="col-md-2">
                                <a class="form-control btn btn-success btn-sm btn-block"
                                   href="@Url.Action("Edit", "Utilisateurs", new {id=Model.ID, page = ViewBag.Page})">@Resources.Edit</a>
                            </div>
                            <div class="col-md-2">
                                <!-- Only PDG can view all users BMS account -->
                                @if (User.IsAuthorized(new[] { RoleType.Pdg, RoleType.ResponsableZone, RoleType.Technicien }))
                                {
                                    <!-- RETURN TO UTILISATEURS LIST -->
                                    <a class="form-control btn btn-primary btn-sm btn-block"
                                       href="@Url.Action("Index", "Utilisateurs", new {page = ViewBag.Page })">@Resources.Cancel</a>
                                }
                                else
                                {
                                    <a class="form-control btn btn-primary btn-sm btn-block" href="@Url.Action("Index", "Home")">Annuler</a>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <style type="text/css">
        #ConfirmPassword, #password {
            z-index: 0;
        }

        #clearPassword, #clearConfirmPassword {
            display: none;
            position: absolute;
            z-index: 100;
        }
    </style>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/password")

    <script type="text/javascript">

        $(document).ready(function () {

            // toggle current user menu item
            $("#title-user").addClass("active");
            $("#menu-user").show();


            $("#show-password").mousedown(function () {
                DisplayPassword($(this), "PassWord", "clearPassword");
            });

            $("#show-password").mouseup(function () {
                HiddePassword("clearPassword");
            });
        });
    </script>


}

SiteBMS/Views/Utilisateurs/Index - Copy.cshtml
@model IEnumerable<SiteBMS.Models.Utilisateur>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RoleUtilisateurs.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prenom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PassWord)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RefLangue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RefId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RoleUtilisateurs.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prenom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Login)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PassWord)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RefLangue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RefId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>