SiteBMS/Models/CarenceReleve.cs
using System.Linq;

namespace SiteBMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CarenceReleve")]
    public partial class CarenceReleve
    {
        public int ID { get; set; }

        public int RefCarenceNorme { get; set; }

        public int RefReleve { get; set; }

        public int? RefComboCarence { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? ValeurAnalyseCarence { get; set; }

        public virtual CarenceNorme CarenceNorme { get; set; }

        public virtual Releve Releve { get; set; }
    }
}

SiteBMS/Controllers/CarenceRelevesController.cs
using SiteBMS.Models;
using SiteBMS.ViewModels;
using System;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Collections.Generic;

namespace SiteBMS.Controllers
{
    public class CarenceRelevesController : BaseController
    {
        // GET: CarenceReleves
        public ActionResult Index()
        {
            var carenceReleves = db.CarenceReleves
                .Include(c => c.CarenceNorme)
                .Include(c => c.Releve);
            return View(carenceReleves.ToList());
        }

        // GET: CarenceReleves List for  releve
        public ActionResult List(int? id, int? page)
        {
            const string sqlQuery =
                @"SELECT C.TYPEID AS RefType, C.Traduction AS Name, B.CarenceCount, B.RefReleve, B.RefParcelle
                                FROM(SELECT CT.ID AS TYPEID, T.Traduction FROM BMS.dbo.CarenceType AS CT
                                    INNER JOIN Traduction AS T ON T.RefElement = CT.Nom_T AND T.RefLangue = @LangueID)
                                AS C LEFT JOIN (SELECT CN.RefType, CR.RefReleve, R.RefParcelle, COUNT(CN.RefType) AS CarenceCount
                                FROM dbo.CarenceReleve AS CR
                                    INNER JOIN dbo.CarenceNorme AS CN ON CR.RefCarenceNorme = CN.ID
                                    INNER JOIN dbo.Releve AS R ON CR.RefReleve = R.ID
                        WHERE CR.RefReleve = @ReleveID
                        GROUP BY CN.RefType, CR.RefReleve, R.RefParcelle) AS B ON C.TYPEID = B.RefType";

            var parameters = new object[]
            {
                new SqlParameter("@ReleveID", id),
                new SqlParameter("@LangueID", User.LanguageId)
            };

            var carenceVm = db.Database.SqlQuery<CarenceTypeViewModel>(sqlQuery, parameters).ToList();
            ViewBag.Releve = db.Releves.Find(id);
            ViewBag.Page = (page ?? 1);

            return View(carenceVm);
        }

        // GET: CarenceReleves/Details/5
        public ActionResult Details(int? id, int? typeId, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Feuilles(1) - Fruits(2) - Rameaux(3)
            // 1 : default
            var typeCarence = (typeId ?? 1);

            // List of all carence of type : typeCarence
            // List<CarenceReleve>
            var carenceList = (from cr in db.CarenceReleves
                               join cn in db.CarenceNormes on cr.RefCarenceNorme equals cn.ID
                               where cn.RefType == typeCarence
                               && cn.RefEspece == cr.Releve.Parcelle.RefComboEspece
                               && cr.RefReleve == id
                               select cr).ToList();

            if (carenceList.Equals(null))
            {
                return HttpNotFound();
            }

            // first in the list
            var carenceReleve = carenceList.FirstOrDefault();

            // ViewModel (no based to model)
            var carenceValuesVm = new CarenceValuesViewModel
            {
                CarenceReleve = carenceReleve,
                TypeCarence = typeCarence,
                Releve = carenceReleve?.Releve,
                RefReleve = carenceReleve?.RefReleve ?? 0,
                EspeceID = carenceReleve?.Releve.Parcelle.RefComboEspece ?? 0
            };

            // fill viewmodel with values
            foreach (var c in carenceList)
            {
                carenceValuesVm.PropertySet(carenceValuesVm, "tbx_" + c.CarenceNorme.RefCarenceElement, c.ValeurAnalyseCarence.ToString());
                carenceValuesVm.PropertySet(carenceValuesVm, "ddl_" + c.CarenceNorme.RefCarenceElement, c.RefComboCarence);
            }

            carenceValuesVm.EspeceID = carenceReleve.Releve.Parcelle.RefComboEspece;

            ViewBag.Page = (page ?? 1);
            InitViewBag(carenceValuesVm.CarenceReleve);

            return View(carenceValuesVm);
        }

        // GET: CarenceReleves/Create id = refReleve, typeId = CarenceType
        public ActionResult Create(int? id, int? typeId, int? page)
        {
            // Feuilles(1) - Fruits(2) - Rameaux(3)
            // 1 : by default
            var typeCarence = (typeId ?? 1);

            var refReleve = (id ?? default(int));

            var releve = db.Releves.Find(refReleve);

            // carenceNorme
            // TODO : only one carenceNorme
            var carenceNorme = (from cn in db.CarenceNormes
                               where cn.RefType == typeCarence
                               && cn.RefEspece == releve.Parcelle.RefComboEspece
                               select cn).FirstOrDefault();

            // new carenceReleve
            var carenceReleve = new CarenceReleve
            {
                RefReleve = refReleve,
                Releve = releve,
                CarenceNorme = carenceNorme,
            };

            // ViewModel (no based to model)
            var carenceValuesVm = new CarenceValuesViewModel
            {
                CarenceReleve = carenceReleve,
                TypeCarence = typeCarence,
                RefReleve = carenceReleve.RefReleve,
                EspeceID = releve.Parcelle.RefComboEspece,
                Releve = releve
            };

            ViewBag.Page = (page ?? 1);

            InitViewBag(carenceValuesVm.CarenceReleve);

            ViewBag.Page = (page ?? 1);
            return View(carenceValuesVm);
        }

        // POST: CarenceReleves/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarenceValuesViewModel carenceReleveVm, int? page)
        {
            var vals = carenceReleveVm.GetValues(carenceReleveVm);
            carenceReleveVm.CarenceReleve = db.CarenceReleves.Find(carenceReleveVm.RefReleve);

            if (ModelState.IsValid)
            {
                SaveReleveCarence(carenceReleveVm, vals);
                return RedirectToAction("List", new { id = carenceReleveVm.RefReleve, page });
            }

            InitViewBag(carenceReleveVm.CarenceReleve);
            ViewBag.Page = page;
            return View(carenceReleveVm);
        }

        // GET: CarenceReleves/Edit/5 (id == id releve, typeID == typeCarence)
        public ActionResult Edit(int? id, int? typeId, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Feuilles(1) - Fruits(2) - Rameaux(3)
            // 1 : default
            var typeCarence = (typeId ?? 1);

            // List of all carence of type : typeCarence
            // List<CarenceReleve>
            var carenceList = (from cr in db.CarenceReleves
                               join cn in db.CarenceNormes on cr.RefCarenceNorme equals cn.ID
                               where cn.RefType == typeCarence
                               && cn.RefEspece == cr.Releve.Parcelle.RefComboEspece
                               && cr.RefReleve == id
                               select cr).ToList();

            if (carenceList.Equals(null))
            {
                return HttpNotFound();
            }

            // first in the list
            var carenceReleve = carenceList.FirstOrDefault();

            // ViewModel (no based to model)
            var carenceValuesVm = new CarenceValuesViewModel
            {
                CarenceReleve = carenceReleve,
                TypeCarence = typeCarence,
                Releve = carenceReleve?.Releve,
                RefReleve = carenceReleve?.RefReleve ?? 0,
                EspeceID = carenceReleve?.Releve.Parcelle.RefComboEspece ?? 0
            };

            // fill viewmodel with values
            foreach (var c in carenceList)
            {
                carenceValuesVm.PropertySet(carenceValuesVm, "tbx_" + c.CarenceNorme.RefCarenceElement, c.ValeurAnalyseCarence.ToString());
                carenceValuesVm.PropertySet(carenceValuesVm, "ddl_" + c.CarenceNorme.RefCarenceElement, c.RefComboCarence);
            }

            if (carenceReleve != null) carenceValuesVm.EspeceID = carenceReleve.Releve.Parcelle.RefComboEspece;
            //carenceValuesVm.TypeCarence = typeCarence;

            ViewBag.Page = (page ?? 1);

            InitViewBag(carenceValuesVm.CarenceReleve);
            return View(carenceValuesVm);
        }

        // POST: CarenceReleves/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CarenceValuesViewModel carenceReleveVm, int? page)
        {
            page = (page ?? 1);

            // get all value in CarenceValuesViewModel instance
            var vals = carenceReleveVm.GetValues(carenceReleveVm);
            carenceReleveVm.CarenceReleve = db.CarenceReleves.Find(carenceReleveVm.CarenceReleve.ID);

            if (ModelState.IsValid)
            {
                SaveReleveCarence(carenceReleveVm, vals);
                return RedirectToAction("List", new { id = carenceReleveVm.RefReleve, page });
            }
            else
            {
                Repositories.ShowStateErrors(ModelState);
                var errors = ModelState.Values.SelectMany(v => v.Errors);
            }

            InitViewBag(carenceReleveVm.CarenceReleve);
            ViewBag.Page = page;

            return View(carenceReleveVm);
        }

        // Save carenceReleve in Database
        private void SaveReleveCarence(CarenceValuesViewModel carenceReleveVm, IEnumerable<Carence> vals)
        {
            // fonctionne pour add mais pas pour edition car dans edit il y a pas de refreleve
            carenceReleveVm.Releve = db.Releves.Find(carenceReleveVm.RefReleve);

            // create all Carence instances in List

SiteBMS/Views/CarenceReleves/Create - Copie.cshtml
@model SiteBMS.Models.CarenceReleve

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CarenceReleve</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RefCarenceNorme, "RefCarenceNorme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RefCarenceNorme", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RefCarenceNorme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RefReleve, "RefReleve", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RefReleve", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RefReleve, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RefComboCarence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RefComboCarence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RefComboCarence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValeurAnalyseCarence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValeurAnalyseCarence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValeurAnalyseCarence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiteBMS/Views/CarenceReleves/Delete.cshtml
@model SiteBMS.Models.CarenceReleve

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarenceReleve</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarenceNorme.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarenceNorme.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Releve.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Releve.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefComboCarence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefComboCarence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValeurAnalyseCarence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValeurAnalyseCarence)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SiteBMS/Views/CarenceReleves/Details - Copie.cshtml
@model SiteBMS.Models.CarenceReleve

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CarenceReleve</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarenceNorme.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarenceNorme.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Releve.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Releve.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefComboCarence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefComboCarence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValeurAnalyseCarence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValeurAnalyseCarence)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SiteBMS/Views/CarenceReleves/Index.cshtml
@model IEnumerable<SiteBMS.Models.CarenceReleve>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CarenceNorme.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Releve.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RefComboCarence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValeurAnalyseCarence)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CarenceNorme.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Releve.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RefComboCarence)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValeurAnalyseCarence)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID })
        </td>
    </tr>
}

</table>

SiteBMS/Views/CarenceReleves/List.cshtml
@model IEnumerable<SiteBMS.ViewModels.CarenceTypeViewModel>

@{
    //var ViewBag.Releve = Model.First();
    ViewBag.Title = Resources.Analyzes +  " : " + ViewBag.Releve.Nom;
    ViewBag.DateReleve = ViewBag.Releve.DateReleve.ToString("dd MMMM yyyy");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <!-- BREADCRUMB Releves/List/328?page=1 -->
                <h2>
                    <!-- List des relevés de la parcelle -->
                    <a href="@Url.Action("List", "Releves", new {id = ViewBag.Releve.RefParcelle, page = ViewBag.Page})"><i class="fa fa-bars"></i> @Resources.StatementS</a>
                    <i class="fa fa-chevron-right" style="font-size: 0.8em;"></i>
                    @ViewBag.Title <small>@Resources.DateOfStatement : @ViewBag.DateReleve</small>
                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2">
                    <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-sm-12 table-responsive">
                                <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                                    <thead>
                                        <tr class="row">
                                            <th class="col-md-4">
                                                @Html.DisplayNameFor(model => model.First().Name)
                                            </th>
                                            <th class="col-md-4">
                                                @Html.DisplayNameFor(model => model.First().CarenceCount)
                                            </th>
                                            <th class="col-md-4">&nbsp;</th>
                                        </tr>
                                    </thead>

                                    @foreach (var item in Model)
                                    {
                                    <tr class="row capitalize">

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @if (item.CarenceCount > 0)
                                                {
                                                @Html.DisplayFor(modelItem => item.CarenceCount)
                                                }
                                                else
                                                {
                                                @Html.ActionLink(Resources.Add, "Create", "CarenceReleves", new {id = ViewBag.Releve.ID, typeID = item.RefType, page = ViewBag.Page}, new {@class = "btn btn-success btn-xs" })
                                                }
                                        </td>
                                        <td>
                                            @if (Request.IsAuthenticated && item.CarenceCount > 0)
                                                {
                                                    //&& User.IsInRole("Admin")
                                                <div class="text-center">
                                                    @Html.ActionLink(Resources.Edit, "Edit", new {id = item.RefReleve, typeID = item.RefType, page = ViewBag.Page}, new {@class = "btn btn-info btn-xs" })
                                                    @Html.ActionLink(Resources.Detail, "Details", new {id = item.RefReleve, typeID = item.RefType, page = ViewBag.Page}, new {@class = "btn btn-default btn-xs" })
                                                </div>
                                                }
                                                else
                                                {
                                                <span>&nbsp;</span>
                                                }
                                        </td>
                                    </tr>
                                    }
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            @*@Html.ActionLink("Retour", "List", "Releves", new { id = ViewBag.Releve.RefParcelle, page = ViewBag.Page }, new { @class = "btn btn-primary btn-sm" })*@
                            <a class="btn btn-primary btn-sm"
                               href="@Url.Action("List", "Releves", new { id = ViewBag.Releve.RefParcelle, page = ViewBag.Page })"><i class="fa fa-arrow-left"></i>&nbsp;Retour</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $(document).ready(function () {

            // toggle current customer menu item
            $("#title-customer").addClass("active");
            $("#menu-customer").show();

            // LIST DES PARCELLES DU CLIENT
            $("#menu-parcel").show();
            $("#list-parcel").attr("href", "/Parcelles/List/" + @ViewBag.Releve.Parcelle.RefClient);

            // LIST DES RELEVE DE LA PARCELLE
            $("#menu-releve").show();
            $("#list-releve").attr("href", "/Releves/List/" + @ViewBag.Releve.Parcelle.ID);
    });

    </script>


}