SiteBMS/ViewModels/TranslateViewModel.cs
namespace SiteBMS.ViewModels
{
    using System;
    using System.ComponentModel.DataAnnotations;

    [Serializable]
    public class TranslateViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Cle { get; set; }

        [Required]
        [StringLength(1000)]
        public string FR { get; set; }

        [StringLength(1000)]
        public string IT { get; set; }

        [StringLength(1000)]
        public string ES { get; set; }

        [StringLength(1000)]
        public string DE { get; set; }

        [StringLength(1000)]
        public string GB { get; set; }

        [StringLength(1000)]
        public string PT { get; set; }

        //[StringLength(1000)]
        //public string AR { get; set; }

        [StringLength(1000)]
        public string NL { get; set; }
    }
}

SiteBMS/Controllers/TranslateController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using SiteBMS.Models;
using SiteBMS.ViewModels;

namespace SiteBMS.Controllers
{
    public class TranslateController : BaseController
    {
        // GET: TranslateViewModels
        public ActionResult Index(int? page, string searchString, string currentFilter, string sortOrder, string emptyWord)
        {
            ViewBag.SortOrder = string.IsNullOrEmpty(sortOrder) ? "SortDesc" : "";
            ViewBag.EmptyWord = emptyWord;


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;


            var translation1 = (from t in db.Traductions
                                from it in db.Traductions.Where(it => it.RefElement == t.RefElement && it.RefLangue == 2).DefaultIfEmpty()
                                from es in db.Traductions.Where(es => es.RefElement == t.RefElement && es.RefLangue == 3).DefaultIfEmpty()
                                from de in db.Traductions.Where(de => de.RefElement == t.RefElement && de.RefLangue == 4).DefaultIfEmpty()
                                from gb in db.Traductions.Where(gb => gb.RefElement == t.RefElement && gb.RefLangue == 5).DefaultIfEmpty()
                                from pt in db.Traductions.Where(pt => pt.RefElement == t.RefElement && pt.RefLangue == 6).DefaultIfEmpty()
                                from nl in db.Traductions.Where(nl => nl.RefElement == t.RefElement && nl.RefLangue == 8).DefaultIfEmpty()
                                where t.RefLangue == 1 && t.RefElement > 0
                                select new
                                {
                                    Cle = t.Cle ?? "",
                                    Id = t.RefElement,
                                    FR = t.Traduction1,
                                    IT = it.Traduction1,
                                    ES = es.Traduction1,
                                    DE = de.Traduction1,
                                    GB = gb.Traduction1,
                                    PT = pt.Traduction1,
                                    NL = nl.Traduction1
                                });

            // Count the percentage progress of each language
            ViewBag.TermesCount = translation1.Count();
            ViewBag.FRCount = translation1.Count(c => c.FR.Length > 0) * 100 / ViewBag.TermesCount;
            ViewBag.ITCount = translation1.Count(c => c.IT.Length > 0) * 100 / ViewBag.TermesCount;
            ViewBag.ESCount = translation1.Count(c => c.ES.Length > 0) * 100 / ViewBag.TermesCount;
            ViewBag.DECount = translation1.Count(c => c.DE.Length > 0) * 100 / ViewBag.TermesCount;
            ViewBag.GBCount = translation1.Count(c => c.GB.Length > 0) * 100 / ViewBag.TermesCount;
            ViewBag.PTCount = translation1.Count(c => c.PT.Length > 0) * 100 / ViewBag.TermesCount;
            ViewBag.NLCount = translation1.Count(c => c.NL.Length > 0) * 100 / ViewBag.TermesCount;

            // filter by empty word
            switch (emptyWord)
            {
                case "Cle": translation1 = translation1.Where(t => t.Cle.Length == 0).Select(c => c); break;
                case "FR": translation1 = translation1.Where(t => t.FR.Length == 0).Select(c => c); break;
                case "IT": translation1 = translation1.Where(t => t.IT.Length == 0).Select(c => c); break;
                case "ES": translation1 = translation1.Where(t => t.ES.Length == 0).Select(c => c); break;
                case "DE": translation1 = translation1.Where(t => t.DE.Length == 0).Select(c => c); break;
                case "GB": translation1 = translation1.Where(t => t.GB.Length == 0).Select(c => c); break;
                case "PT": translation1 = translation1.Where(t => t.PT.Length == 0).Select(c => c); break;
                case "NL": translation1 = translation1.Where(t => t.NL.Length == 0).Select(c => c); break;
            }

            var translation = translation1.AsEnumerable().Select(x => new TranslateViewModel
            {
                Cle = x.Cle,
                Id = x.Id,
                FR = x.FR,
                IT = x.IT,
                ES = x.ES,
                DE = x.DE,
                GB = x.GB,
                PT = x.PT,
                NL = x.NL
            });

            // search in cle and traduction field
            if (!string.IsNullOrEmpty(searchString))
            {
                translation = translation.Where(
               t => t.Cle.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.FR.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.IT.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.ES.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.DE.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.GB.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.PT.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase)
            || t.NL.StartsWith(searchString, StringComparison.InvariantCultureIgnoreCase));
            }

            // filter oder by
            switch (sortOrder)
            {
                case "SortDesc":
                    translation = translation.OrderByDescending(s => s.Cle);
                    break;
            }

            var pageNumber = (page ?? 1);
            return View(translation.ToPagedList(pageNumber, 10));
        }

        // GET: TranslateViewModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TranslateViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Cle,FR,IT,ES,DE,GB,PT,NL")] TranslateViewModel translateViewModel)
        {
            if (ModelState.IsValid)
            {
                //db.TranslateViewModels.Add(translateViewModel);

                int maxId = db.Traductions.Max(u => u.RefElement) + 1;

                var fr = new Traduction()
                {
                    RefElement = maxId,
                    Cle = translateViewModel.Cle,
                    RefLangue = 1,
                    Culture = "fr",
                    Traduction1 = translateViewModel.FR,
                    IsDefaut = true
                };

                db.Traductions.Add(fr);
                if (db.SaveChanges() > 0)
                {
                    var langues = new int[] { 2, 3, 4, 5, 6, 8 };
                    foreach (var langue in langues)
                    {
                        var item = new Traduction()
                        {
                            RefElement = maxId,
                            Cle = translateViewModel.Cle,
                            Traduction1 = translateViewModel.FR?.Trim() ?? "",
                            IsDefaut = false,
                            RefLangue = langue
                        };

                        switch (langue)
                        {
                            case 2: // IT
                                item.Culture = "it";
                                item.Traduction1 = translateViewModel.IT?.Trim() ?? "";
                                break;

                            case 3: // ES
                                item.Culture = "es";
                                item.Traduction1 = translateViewModel.ES?.Trim() ?? "";
                                break;

                            case 4: // DE
                                item.Culture = "de";
                                item.Traduction1 = translateViewModel.DE?.Trim() ?? "";
                                break;

                            case 5: // GB
                                item.Culture = "gb";
                                item.Traduction1 = translateViewModel.GB?.Trim() ?? "";
                                break;

                            case 6: // PT
                                item.Culture = "pt";
                                item.Traduction1 = translateViewModel.PT?.Trim() ?? "";
                                break;

                            case 8: // NL
                                item.Culture = "nl";
                                item.Traduction1 = translateViewModel.NL?.Trim() ?? "";
                                break;
                        }

                        db.Traductions.Add(item);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(translateViewModel);
        }

        // POST: Add Distributor
        // http://vault.lozanotek.com/archive/2010/04/16/posting_json_data_to_mvc_controllers.aspx
        [HttpPost]
        public ActionResult SaveTranslate(TranslateViewModel translate)
        {
            // ajouter auto les langues manquante
            if (translate != null && translate.Id > 0)
            {
                var traduction = db.Traductions.Where(t => t.RefElement == translate.Id).ToList();

                foreach (var item in traduction)
                {
                    Debug.WriteLine(item.RefLangue);

                    // save key if not null
                    if (!string.IsNullOrEmpty(translate.Cle))
                        item.Cle = translate.Cle.Trim();

                    switch (item.RefLangue)
                    {

SiteBMS/Views/Translate/Create.cshtml
@model SiteBMS.ViewModels.TranslateViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nouveau</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Cle, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mot clé en anglais sans espace ni caractère spéciaux" } })
                @Html.ValidationMessageFor(model => model.Cle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.FR, new { htmlAttributes = new { @class = "form-control", @placeholder = "Français" } })
                @Html.ValidationMessageFor(model => model.FR, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.GB, new { htmlAttributes = new { @class = "form-control", @placeholder = "Anglais" } })
                @Html.ValidationMessageFor(model => model.GB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.IT, new { htmlAttributes = new { @class = "form-control", @placeholder = "Italien" } })
                @Html.ValidationMessageFor(model => model.IT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ES, new { htmlAttributes = new { @class = "form-control", @placeholder = "Espagnol" } })
                @Html.ValidationMessageFor(model => model.ES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.DE, new { htmlAttributes = new { @class = "form-control", @placeholder = "Allemand" } })
                @Html.ValidationMessageFor(model => model.DE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PT, new { htmlAttributes = new { @class = "form-control", @placeholder = "Portugais" } })
                @Html.ValidationMessageFor(model => model.PT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.NL, new { htmlAttributes = new { @class = "form-control", @placeholder = "Néerlandais" } })
                @Html.ValidationMessageFor(model => model.NL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-info btn-sm" />
            </div>
        </div>
    </div>
}

<div class="col-md-4 col-md-offset-1">
    @*@Html.ActionLink("Retour", "Index", null, new {@class= "btn btn-primary btn-sm"})*@
    <a class="btn btn-primary btn-sm"
       href="@Url.Action("Index", "Translate")"><i class="fa fa-arrow-left"></i>&nbsp;Retour</a>
</div>